// Generated by CoffeeScript 1.6.3
(function() {
  var root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.TMG = {};

  root.canvas;

  root.stage;

  root.exportRoot;

  $(function() {
    var actionTAMAGO, customboxOption, isWebkitSpeechSupported, tamagoAction;
    root.init = function() {
      var canvas, exportRoot, stage;
      canvas = document.getElementById("tamagoArea");
      exportRoot = new lib.tamago();
      stage = new createjs.Stage(canvas);
      stage.addChild(exportRoot);
      stage.update();
      createjs.Ticker.setFPS(lib.properties.fps);
      return createjs.Ticker.addEventListener("tick", stage);
    };
    isWebkitSpeechSupported = function() {
      if (document.createElement('input').webkitSpeech) {
        console.log('webkitSpeech Disable');
        return $('#webkitSpeechStatus').text('対応していません↓↓');
      } else {
        console.log('webkitSpeech Enable');
        return $('#webkitSpeechStatus').text('対応しています!');
      }
    };
    root.speechCangeEvent = function(inputText) {
      console.log('speech -> ' + inputText);
      return tamagoAction(inputText);
    };
    tamagoAction = function(inputText) {
      var happyWords;
      happyWords = /楽|笑|喜|嬉|たのしい|うれしい/;
      console.log(inputText);
      switch (true) {
        case inputText.match(happyWords) !== null:
          return actionTAMAGO('standup');
        default:
          return actionTAMAGO('shock');
      }
    };
    actionTAMAGO = function(type) {
      console.log(type);
      root.TMG.isStanby = true;
      return root.TMG.actionType = type;
    };
    root.init();
    isWebkitSpeechSupported();
    customboxOption = {
      url: '#modal',
      effect: 'fadein',
      overlayColor: '#FFF',
      overlayOpacity: 1,
      speed: 1000,
      close: function() {
        return $('#wrap').fadeIn(1000);
      }
    };
    return $.fn.custombox(customboxOption);
  });

}).call(this);
